//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edge.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of &apos;{0}&apos; failed..
        /// </summary>
        internal static string ActivationFailedException_DefaultMessage {
            get {
                return ResourceManager.GetString("ActivationFailedException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed..
        /// </summary>
        internal static string CompilationFailedException_DefaultMessage {
            get {
                return ResourceManager.GetString("CompilationFailedException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed due to {0} errors and {1} warnings..
        /// </summary>
        internal static string CompilationFailedException_MessageWithErrorCounts {
            get {
                return ResourceManager.GetString("CompilationFailedException_MessageWithErrorCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;{0}&quot; /&gt;.
        /// </summary>
        internal static string ErrorPage_LinkComponent {
            get {
                return ResourceManager.GetString("ErrorPage_LinkComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;error-list&quot;&gt;
        ///    {0}
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string ErrorPage_ListComponent {
            get {
                return ResourceManager.GetString("ErrorPage_ListComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0}&lt;/li&gt;.
        /// </summary>
        internal static string ErrorPage_ListItemComponent {
            get {
                return ResourceManager.GetString("ErrorPage_ListItemComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;An error has occurred&lt;/title&gt;
        ///    {0}
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;icon&quot;&gt;:(&lt;/div&gt;
        ///    &lt;div class=&quot;generic&quot;&gt;An error has occurred.&lt;/div&gt;
        ///    &lt;div class=&quot;message&quot;&gt;{1}: {2}&lt;/div&gt;
        ///    {3}
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ErrorPage_Template {
            get {
                return ResourceManager.GetString("ErrorPage_Template", resourceCulture);
            }
        }
    }
}
